FormidableLabs/react-native-ama

- .github/workflows/deploy-docs.yml
- website/docusaurus.config.js
- website/formideploy.config.js
- website/package.json
- website/yarn.lock
Formideploy setup for docs. If working properly, should deploy docs to `formidable.com/open-source/react-native-ama`.
> Formideploy setup for docs

- ios/Ama.m
- ios/Ama.swift
- lib/internal/logger.ts
- lib/providers/AMAProvider.test.tsx
- lib/providers/AMAProvider.tsx
set all the accessibility values in once to avoid multiple re-renders
> chore: reduce re-renders

- example/ios/Podfile.lock
- example/src/screens/Form.screen.tsx
Fixes crash when you open Form.Screen in the example project.
> fix: crash in the form example

- android/src/main/java/com/reactnativeama/components/AmaFlatListWrapper.kt
This prevents an Android 7 crash with the following stack track.
I'm not sure if there are any accessibility related consequences of this change though
```
07-28 23:10:39.048  6247  6247 E AndroidRuntime: java.lang.NoSuchMethodError: No virtual method setFocusable(I)V in class Lcom/reactnativeama/components/AmaFlatListWrapper; or its super classes (declaration of 'com.reactnativeama.components.AmaFlatListWrapper' appears in /data/app/com.xxxx.xxxx.dev-2/base.apk:classes8.dex)
07-28 23:10:39.048  6247  6247 E AndroidRuntime:        at com.reactnativeama.components.AmaFlatListWrapper.<init>(AmaFlatListWrapper.kt:13)
07-28 23:10:39.048  6247  6247 E AndroidRuntime:        at com.reactnativeama.components.AmaFlatListWrapperManager.createViewInstance(AmaFlatListWrapperManager.kt:14)
07-28 …
```
> fix: add setFocusable overrides

- .npmignore
- app.config.js
> chore: add expo support

- docs/components/AutofocusContainer.md
- docs/components/DynamicFlatList.mdx
- docs/components/FlatList.mdx
- docs/components/FormSubmit.md
- docs/hooks/useTextInput.md
- lib/internal/logger.rules.ts
I was clicking around through the docs and noticed a dead link, so here is a PR with an update.
PS: This library looks really promising - looking forward to trying it out on my next project!
> docs: Update links to lists/grids guidelines

- .eslintrc.js
- .npmignore
- docs/introduction/getting-started.md
- example/src/components/CTAPressable.tsx
- lib/components/Pressable.tsx
- lib/hooks/usePressable.ts
- lib/internal/useButtonChecks.ts
> fix Pressable type

- lib/components/BottomSheet.test.tsx
- lib/components/BottomSheet.tsx
- lib/providers/AMAProvider.tsx
Fix some re-rendering issue caused by mocking safe area with jest
> Jest support

- .changeset/config.json
Need to add title to the `.changeset/config.json` in order to remove this error: https://github.com/FormidableLabs/react-native-ama/actions/runs/5201685297/jobs/9382205451#step:10:52
> fix: changesets config update

- .changeset/config.json
- .github/workflows/release.yml
Reverting #103 and adding title and commit message to GitHub Action Workflow directly
> fix: changesets workflow update

- docs/guidelines/lists-grids.md
> Fix list-grids links from 404

- docs/components/Form.md
- docs/guidelines/headers.md
- lib/providers/Form.tsx
- package.json
Add `focusFirstInvalidField` method for the Form component.
Fix documentation for #106
> feat: Improve forms

- android/build.gradle
> chore: remove jcenter

- android/build.gradle
> chore: remove jcenter from build.gradle

- docs/guidelines/minimum-size.md
The current link was broken, this updates that.
> Update customising-the-log-levels link on minimum-size.md

- examples/shared/index.ts
- examples/shared/package.json
- examples/shared/src/components/BackButton.tsx
- examples/shared/src/components/CTAPressable.tsx
- examples/shared/src/components/CTATouchableOpacity.tsx
- examples/shared/src/components/CTATouchableWithoutFeedback.tsx
- examples/shared/src/components/Header.tsx
- examples/shared/src/components/Spacer.tsx
- examples/shared/src/screens/BottomSheet.screen.tsx
- examples/shared/src/screens/ExpandablePressableScreen.tsx
- examples/shared/src/screens/FlatList.screen.tsx
- examples/shared/src/screens/FlatListDynamic.screen.tsx
- examples/shared/src/screens/FlatListStatic.screen.tsx
- examples/shared/src/screens/Form.screen.tsx
- examples/shared/src/screens/Home.screen.tsx
- examples/shared/src/screens/Pressable.screen.tsx
- examples/shared/src/screens/Text.screen.tsx
- examples/shared/src/screens/TouchableOpacity.screen.tsx
- examples/shared/src/screens/TouchableWithoutFeedback.screen.tsx
- examples/shared/src/screens/UseAMAContext.screen.tsx
- examples/shared/src/screens/UseAnimationScreen.tsx
- examples/shared/src/screens/UseReanimatedTimingScreen.tsx
- examples/shared/src/screens/UseTimedAction.screen.tsx
- examples/shared/src/theme.ts
- examples/shared/tsconfig.build.json
- examples/shared/tsconfig.json
- package.json
This PR is to break out code to be shared between react native and expo
> chore: split out shared components into `shared-ui` package

- packages/extras/src/hooks/useKeyboard.ts
This PR adds type to the useKeyboard hook which is necessary for builds to run
> chore: added types to handleKeyboardEvent callback

- package.json
- packages/animations/package.json
- packages/animations/tsconfig.build.json
- packages/core/package.json
- packages/core/tsconfig.build.json
- packages/extras/package.json
- packages/extras/tsconfig.build.json
- packages/forms/package.json
- packages/forms/tsconfig.build.json
- packages/internal/package.json
- packages/internal/tsconfig.build.json
- packages/lists/package.json
- packages/lists/tsconfig.build.json
- packages/react-native/package.json
- packages/react-native/tsconfig.build.json
- tsconfig.json
This PR updates build configs and package.json's for the various packages we will deploy under `@react-native-ama/...` namespace
Fixes # (issue)
> Update package builds to work for mono-repo

- README.md
This updates the readme to NearForm site and banner
> Fixed README links and banner

- packages/core/docs/AMAProvider.md
- packages/core/docs/core.md
- packages/core/docs/hooks/useAMAContext.md
- packages/core/docs/hooks/useFocus.md
- packages/core/docs/hooks/useTimedAction.md
This PR updates core package docs usage and links
Tested running doc site
> Updates core docs usage and links

- packages/forms/docs/FormField.md
- packages/forms/docs/FormSubmit.md
- packages/forms/docs/FormSwitch.md
- packages/forms/docs/useTextInput.md
This PR adds and updates `form` package docs
> Update and Add `form` package docs

- packages/animations/docs/components/AnimatedContainer.md
- packages/animations/docs/hooks/useReanimatedTiming.md
- website/versioned_docs/version-0.7.x/components/AnimatedContainer.md
- website/versioned_docs/version-0.7.x/hooks/useReanimatedTiming.md
Reanimated has updated their documentation to and thus some links have broken, this PR fixes those links
> fixes broken `react-native-reanimated` doc links

- packages/animations/docs/components/AnimatedContainer.md
- packages/animations/docs/hooks/useReanimatedAnimationBuilder.md
- packages/animations/src/hooks/useReanimatedAnimationBuilder.ts
This PR documents the useReanimatedAnimationBuilder hook
> Add previously undocumented `useReanimatedAnimationBuilder` hook doc

- README.md
- packages/core/docs/core.md
- website/docs/ama/intro.md
This PR prepares the readme for the next version of AMA as well as making some changes to the intro AMA doc
> Update docs readme and intro for next version

- website/docusaurus.config.ts
- website/package.json
- website/yarn.lock
Adds gtag configuration to the docusaurus config file.
> Added gtag config

- examples/shared/src/screens/UseReanimatedTimingScreen.tsx
This PR fixes an error in our example of useReanimatedTiming Screen 
|              Before                |              After                |
| ---------------------------------- | --------------------------------- |
| <img width="370" alt="image" src="https://github.com/user-attachments/assets/e56190d5-6fd7-4855-8994-0d486ec7e5ad" />   | <img width="370" alt="image" src="https://github.com/user-attachments/assets/6cbe6e87-657f-4b82-8e54-80d36bb34be4" />   |
> fixes AMA example error on useReanimatedTiming screen (adds role and link to screen)

- examples/expo/package.json
- yarn.lock
This PR upgrades our expo example app to the meet the version of our bare example app
> upgrade expo example app to 50.0.20 (RN 0.73.6) from 49.0.10 (RN 0.72.4)

- .changeset/config.json
- package.json
- yarn.lock
This PR updates our changesets to automate release managing versioning in a monorepo
> update Changesets versioning and config

- examples/shared/package.json
This PR updates the dependencies for shared-ui package which was unnecessary
> remove package dependencies for shared-ui pacakge

- .github/workflows/release.yml
This PR updates our token for publishing to new scoped packages on NPM repo
> update token name for publishing

- .changeset/calm-snails-invite.md
- .changeset/flat-phones-change.md
- babel.base.js
- examples/bare/babel.config.js
- examples/expo/babel.config.js
- package.json
- packages/core/babel.config.js
- packages/forms/babel.config.js
This PR allows us to lint any js files added to the repo
> fix linting for js files

- website/docusaurus.config.ts
This PR makes the next version the current version without the need to cut a new next version
> docs: added next version as current

- website/checklist/button.md
> fix button checklist

- website/docs/ama/intro.md
This change is a simple documentation update that improves upon the alternative text provided for images in the `intro.md` file for accessibility, and makes other additional changes to the file for more ease of reading and consistency.
> [DOCS] Updating introduction documentation file

- README.md
> Update readme checklist and guidelines descriptions

- packages/extras/package.json
Update min version for `react-native-gesture-handler` in `extras` package
> Update min version for `react-native-gesture-handler` in `extras` package

- .changeset/six-kings-complain.md
- examples/shared/src/screens/FlatListDynamic.screen.tsx
- packages/forms/src/components/FormField.tsx
- packages/forms/src/components/FormSwitch.tsx
- packages/forms/src/components/TextInput.tsx
- packages/forms/src/hooks/useTextInput.ts
- packages/forms/src/index.ts
This PR allows the suppression of form provider errors on TextInput components
> Extend Form provider suppressedError to TextInput component

- examples/expo/package.json
- package.json
- yarn.lock
Upgrade existing expo example app to latest 51 version
Tested Android and iOS apps with Expo Go
> upgrade expo example app to 51.0.39 (RN 0.74.5) from 50.0.20 (RN 0.73.6)

- examples/README.md
- examples/bare/README.md
- examples/expo/README.md
This PR add's readmes to examples directory
> Add README's to examples

- examples/bare/metro.config.js
Adds recommended reanimated setup for metro to allow errors
> Add reanimated recommended metro setup

- .eslintrc.js
- package.json
- yarn.lock
This PR updates the eslint testing for package
`yarn lint` was tested in the route which runs linting for all packages
> Updated linting for packages

- website/docs/ama/getting-started.md
Tweaks package description in the docs getting started
> docs: updated package descriptions in getting started

- .changeset/small-forks-run.md
- .github/workflows/run-tests.yml
- packages/core/package.json
- packages/core/scripts/create-config.ts
- packages/core/src/postinstall.js
- packages/core/tsconfig.build.json
- packages/internal/src/utils/logger.ts
Fixes the generation of the rules/config file when installing the package, and removes the need to symlink the files.
Have to update docs still
Fixes # (issue)
Tested by packaging files locally and running in a sample app
> task: bring back rules file

- .changeset/config.json
- CONTRIBUTING.md
- examples/bare/package.json
This PR adds new `changesets` config to bump all packages to the same version when a change is made to one package. This will help with any future debugging of consumers issues. contriubution docs have also been added with updated versioning strategy.  
Example apps were also added to changesets
> chore: Updated versioning strategy and `changesets` config

- website/docs/ama/config-file.md
- website/docs/ama/getting-started.md
- website/versioned_docs/version-0.7.x/introduction/getting-started.md
Updated docs to support configs within monorepos. This change needs to follow PR 
Tested by running docs
> task: update docs for ama rules

- packages/internal/src/index.ts
- packages/internal/src/utils/platformHelpers.ts
This PR adds platform helpers to internal for ease of use.
> Adds Platform helpers to `internal` package

- packages/extras/docs/components/BottomSheet.md
- packages/extras/docs/components/Carousel.md
- website/versioned_docs/version-0.7.x/components/BottomSheet.md
Fixes capitalisation typo in docs
> docs: fixes typo with capitalisation

- .changeset/honest-shirts-guess.md
- .changeset/metal-poets-whisper.md
- .changeset/sharp-mugs-poke.md
- examples/bare/src/AppNavigator.tsx
- examples/expo/src/AppNavigation.tsx
- examples/shared/index.ts
- examples/shared/package.json
- examples/shared/src/screens/Home.screen.tsx
- examples/shared/src/screens/Loading.screen.tsx
- packages/core/src/index.ts
- packages/extras/docs/components/Loading.md
- packages/extras/src/components/Loading.tsx
- packages/extras/src/index.ts
This PR adds a `<Loading />` component which announces when a loading state is present
> Adds new accessible `<Loading />` component and accompanying docs

- website/package.json
- website/yarn.lock
Update TS package to latest version for website
> docs: TS package update on website

- website/src/components/landing/landing-featured-projects.tsx
- website/src/pages/index.tsx
This PR fixes the layout for landing featured projects layout when viewed on large screen.
Ran website locally
> docs: updated docs landing featured projects layout
