example/ios/Podfile.lock, ios/Ama.swift
Fixes this warning on iOS. From new versions of react native you need to explicitly declare whether or not your module requires main queue setup.
=> chore: add main queue setup for iOS

lib/components/BottomSheet.test.tsx, lib/components/BottomSheet.tsx
The Modal `onRequestClose` prop was calling the `onClose` callback with an `event` argument.
This PR calls `onClose` with no argument, as documented in the types.
=> Fix: ensure there is no `onClose` argument

lib/hooks/usePressable.ts
Currently the user-defined `onLayout` is getting overridden in dev mode. This ensures the `onLayout` gets called if defined.
=> Ensure onLayout is called in __DEV__ mode

lib/components/AutofocusContainer.tsx
The type for `viewProps` was incorrect. In the component definition it was used as the [`rest parameter` ](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions/rest_parameters) but defined in the `AutofocusContainerProps` type as a parameter
Either
```typescript
type AutofocusContainerProps = React.PropsWithChildren<
{ wrapChildrenInAccessibleView?: true } & ViewProps
>;
export const AutofocusContainer = ({
children,
wrapChildrenInAccessibleView = true,
...viewProps
}: AutofocusContainerProps)
```
Or 
```typescript
type AutofocusContainerProps = React.PropsWithChildren<{
wrapChildrenInAccessibleView?: boolean;
viewProps?: ViewProps;
}>;
export const AutofocusContainer = ({
children,
wrapChildrenInAccessibleView = true,
viewProps
}: AutofocusContainerProps)
``` …
=> Fixing viewProps type

android/build.gradle
It seems that other packages use `kotlin_version` instead of `kotlinVersion`, so this PR allows AMA to use either
=> fix: use `kotlin_version` from root project

docs/components/TextInput.mdx
Corrects the documentation for `errorPosition` prop for the `TextInput` component.
=> Fix `errorPosition` documentation for TextInput component

example/android/app/build.gradle, example/android/build.gradle, example/ios/Podfile.lock, example/package-lock.json, example/package.json, example/src/App.tsx, example/src/screens/Home.screen.tsx, example/src/screens/UseAMAContext.screen.tsx, example/src/types.ts, example/yarn.lock, lib/providers/AMAProvider.tsx, yarn.lock
The initial value of `isScreenReaderEnabled` returned from `Accessablity.isScreenReaderEnabled()` is often overwritten by a setState triggered from the `checkAndroidAnimationStatus` function.
This PR adjusts the state setting logic to merge the updated state into the current state correctly.
A new page has also been added to the example app to make it easier to demo the values from `useAMAContext`
This PR also tweaks the example project to get it building on iOS and Android again.
=> fix: Correct initial `isScreenReaderEnabled` value and fix example project build

.github/workflows/deploy-docs.yml, website/docusaurus.config.js, website/package.json
This PR sets up Vercel for staging previews for docs (instead of Surge), and we'll soon use the Vercel deploy for prod docs as well.
=> Vercel docs setup

docs/introduction/getting-started.md
The required dependency has a typo.
=> fix: Typo in getting started docs

.changeset/config.json, .changeset/wise-foxes-punch.md, .github/workflows/release.yml, CONTRIBUTING.md, README.md, package.json, yarn.lock
- Setting up a `release.yml` GitHub Workflow so that we can publish to NPM in an automated fashion.
- Added `changesets` as the tool to control semantic-release versioning for NPM publishing.
- Removed `release-it` as the tool to control semantic-release versioning for NPM publishing
- Added the following in order to add Provenance verification badge on [this NPM page](https://www.npmjs.com/package/react-native-ama)
```
"publishConfig": {
"provenance": true
}
```
- Added a `NPM_TOKEN` to the settings of this repo.
- Created a `CONTRIBUTING.md` guide
=> fix: removing release-it, adding changeset, publish provenance

docs/introduction/config-file.md
The incorrect name was referenced in the docs for ama.rules.json
=> Update ama.rules.json file name in config-file.md 

docs/introduction/config-file.md
A bunch of the links in the default rules were broken. I have updated these.
In some cases I have linked to the corresponding heading in the page, instead of just the page. Happy to remove the anchor links and just link directly to the page.
=> fix links in default rules in file config-file.md

docs/hooks/useTextInput.md
The example suggests `useTextInput` hook can be called without  any props. This PR updates the example to reflect there are required props
=> suggested update to useTextInput example

packages/forms/src/components/FormSubmit.tsx
This PR fixes the issue that if FormSubmit wraps any children with a event like Pressable or Touchable Opacity then FormSubmit will not trigger the `onPress={submitForm}`.
I have added `pointerEvents` before the `{...props}` spread to allow consumers to overwrite this behaviour. Even though this would defeat the purpose of the Component
=> fix: FormSubmit not capturing event issue

examples/bare/babel.config.js, examples/bare/ios/Podfile.lock, examples/bare/package.json, examples/bare/yarn.lock
This PR adds reanimated to the rn example app
=> chore: add reanimated to rn example app

packages/core/src/components/AMAProvider.integration.test.tsx, packages/core/src/components/AMAProvider.tsx, packages/core/src/hooks/useChecks.test.ts, packages/core/src/hooks/useChecks.ts, packages/core/src/index.ts, packages/forms/src/components/Form.tsx
This PR improves our error report for context so that useContext always returns the correct context if in a provider. It also updates the AMAProvider Types to be more accurate and fixes some tests.
=> feat: improved context types and errors

examples/shared/src/screens/Form.screen.tsx, packages/forms/src/components/FormSwitch.tsx, packages/forms/src/index.ts, packages/react-native/src/components/SwitchListItem.tsx, packages/react-native/src/index.ts
This PR  `Form.Switch` component which wraps `SwitchListItem` component with `FormField` component to handle all useForm props. This allows `SwitchListItem` to be used outside of `FormProvider`
=> feat: creates helper `Form.Switch` component from `SwitchListItem` component

docs/guidelines/accessibility-label.md
I was just going through the docs and found this small issue in Markdown where the link for `TouchableWithoutFeedback` in [Accessibility Label](https://formidable.com/open-source/react-native-ama/guidelines/accessibility-label) is broken.
=> docs: fix link in accessibility label page

website/docusaurus.config.ts, website/guidelines/accessibility-label.md, website/guidelines/accessibility-role.md, website/guidelines/accessibility-states.md, website/guidelines/animations.md, website/guidelines/bottomsheet.md, website/guidelines/carousel.md, website/guidelines/contrast.md, website/guidelines/focus.md, website/guidelines/forms.md, website/guidelines/headers.md, website/guidelines/lists-grids.md, website/guidelines/minimum-size.md, website/guidelines/text.md, website/guidelines/timed-actions.md, website/sidebars.ts, website/src/components/AMASection.jsx, website/src/components/devOnly.jsx, website/src/components/index.js, website/src/css/custom.css, website/src/theme/DocItem/TOC/Desktop/AMASidebar.js, website/src/theme/DocItem/TOC/Desktop/index.js, website/src/theme/MDXComponents.js, yarn.lock
- Fix accessibility issue on some color contrast
- Adds "AMA Section" for mobile / tablet devices
- Excludes "index.md" from the custom autogenerated sidebar
- Remove test code in the docusaurus config
=> Fix AMA documentation

examples/shared/src/screens/BottomSheet.screen.tsx, packages/extras/docs/BottomSheet.md, packages/extras/src/components/BottomSheet.tsx, website/versioned_docs/version-0.7.x/components/BottomSheet.md
Allows not wrapping BottomSheet children inside a ScrollView. This allows the dev to have a different type of scrollable container, like FlatList, etc.
Fixes #210
=> Make ScrollView optional

packages/core/src/hooks/useFocus.ts
There are certain cases where findNodeHandle may throw an error. We now catch this and log it when in dev mode instead of crashing the app. 
The focus hook has also been updated to handle on screen loads better where in certain cases it would not focus an element. setTimeout has been added to catch more of these cases.
=> update useFocus Hook to handle animations and catch findNodeHandle errors

packages/core/src/hooks/useButtonChecks.ts, packages/forms/src/components/FormSubmit.test.tsx, packages/react-native/docs/TouchableOpacity.md, packages/react-native/docs/TouchableWithoutFeedback.md, website/versioned_docs/version-0.7.x/components/Pressable.mdx, website/versioned_docs/version-0.7.x/components/TouchableOpacity.md, website/versioned_docs/version-0.7.x/components/TouchableWithoutFeedback.md
This PR addresses some issue with spelling in components and docs
=> fix spelling typos in components and docs

examples/shared/src/screens/Form.screen.tsx, packages/forms/docs/Form.md, packages/forms/src/components/Form.tsx, packages/forms/src/index.ts
This PR pulls in some recent changes to make the Form Provider component more render friendly. It also adds a `focusFieldAt` function to be used by the consumer. Finally I have exported the `isFocused` util from the `form` package (previously only used internally)
=> Update `Form` to reduce re-renders and add `focusFieldAt` function to ref

packages/lists/docs/DynamicFlatList.mdx, packages/lists/docs/FlatList.mdx, packages/lists/docs/ListWrapper.mdx, packages/lists/docs/StaticFlatList.mdx
Adds list docs to list package
=> Add `list` documentation to AMA package

packages/extras/docs/BottomSheet.md, packages/extras/src/components/BottomSheet.tsx
fixes Landscape mode in BottomSheet fails accessibility test #223
Fixes #223 (issue)
=> feat: adds support for `supportedOrientations`

packages/core/docs/core.md, packages/core/docs/hooks/useFocus.md, packages/core/docs/hooks/useTimedAction.md, packages/forms/docs/Form.md, packages/forms/docs/FormField.md, packages/forms/docs/FormSwitch.md, packages/forms/docs/TextInput.mdx, packages/forms/docs/useFormField.md, packages/lists/docs/DynamicFlatList.mdx, packages/lists/docs/FlatList.mdx, packages/lists/docs/ListWrapper.mdx, packages/lists/docs/StaticFlatList.mdx, packages/react-native/docs/ExpandablePressable.mdx, packages/react-native/docs/Pressable.md, packages/react-native/docs/SwitchListItem.mdx, packages/react-native/docs/SwitchWrapper.mdx, packages/react-native/docs/Text.md, packages/react-native/docs/TouchableOpacity.mdx, packages/react-native/docs/hooks/useExpandable.md, packages/react-native/docs/hooks/usePressable.mdx, packages/react-native/docs/hooks/useSwitch.md
Relative links don't work across plugin instances. This fixes cross plugin links to be url links
Tested locally with docusaurus
=> fixes links for new docs

website/docs/ama/config-file.md, website/docs/ama/getting-started.md, website/docs/ama/intro.md, website/docs/ama/usage.md
This PR updates getting started and some links on the home next docs
Ran docusaurus locally
=> Update home docs for `next` version

packages/animations/docs/components/AnimatedContainer.md, packages/animations/docs/components/_category_.json, packages/animations/docs/hooks/_category_.json, packages/animations/docs/hooks/useAnimation.mdx, packages/animations/docs/hooks/useAnimationDuration.md, packages/animations/docs/hooks/useReanimatedTiming.md, packages/animations/docs/utilities/_category_.json, packages/animations/docs/utilities/isMotionAnimation.md
This PR ports and updates and adds animation package docs
Ran docusaurus locally
=> Add `next` version `animation` package docs

packages/animations/docs/components/AnimatedContainer.md, packages/animations/docs/hooks/useAnimation.mdx, packages/animations/docs/hooks/useAnimationDuration.md, packages/animations/docs/hooks/useReanimatedTiming.md, packages/extras/docs/BottomSheet.md, packages/forms/docs/Form.md, packages/forms/docs/FormField.md, packages/forms/docs/FormSubmit.md, packages/forms/docs/useFormField.md, packages/forms/docs/useTextInput.md, packages/react-native/docs/Text.md, packages/react-native/docs/TouchableOpacity.mdx, website/docs/ama/usage.md, website/guidelines/accessibility-label.md, website/guidelines/pour.md, website/versioned_docs/version-0.7.x/introduction/usage.md
Fixing links that are cross plugin to URL links
Ran docusaurus
=> Update docs to use URL links for cross plugin docs

package.json, packages/internal/src/utils/logger.rules.ts
This PR updates links that were previously pointing to Formidables hosted docs now hosted on Nearform commerce. (All links were being redirected anyway but now we just point to the correct docs)
=> Updates links to previous Formidable site not Nearform

.changeset/eighty-planets-think.md, packages/extras/src/hooks/useKeyboard.ts
Updates `useKeyboard` hook argument `shouldHandleKeyboardEvents` to default to `true` thus making it not a required arg for the hook
Documentation update for this PR included in #257
=> Update `useKeyboard` hook to use default argument for `shouldHandleKeyboardEvents`

packages/animations/docs/animations.md, packages/core/docs/core.md, packages/extras/docs/extras.md, packages/forms/docs/forms.md, packages/lists/docs/lists.md, packages/react-native/docs/react-native.md, website/docs/ama/config-file.md, website/docs/ama/getting-started.md, website/docs/ama/index.md, website/docs/ama/usage.md, website/sidebars.ts, website/sidebarsPackages.ts
Updates the docs in a few places I came across when upgrading to 1.0. Adjusts some languages/titlecase consistencies.
=> task: more docs

.github/workflows/release.yml, .github/workflows/run-tests.yml
Updated to the following actions versions:
- checkout@v4
- setup-node@v4
Replaced yarn cache setup that previously used `actions/cache` with `actions/setup-node`
=> chore: update actions to v4

.changeset/fifty-rice-lick.md, .changeset/six-goats-retire.md, packages/core/src/components/AutofocusContainer.tsx, packages/internal/src/index.ts, packages/internal/src/types.ts
Adds workaround where some accessible props are ignored on accessible view for AutofocusContainer. Specifically `accessibilityState`
Tested on Android and iOS example app
=> feat: added accessibility props on AutofocusContainer's Touchable container

examples/shared/src/screens/Loading.screen.tsx
This PR triggers the Loading example on mount of the screen and disables the button while loading
=> feat: added trigger to run loading on mount for Loading example

website/package.json, website/src/components/landing/landing-featured-projects.tsx, website/yarn.lock
This PR updates to the latest `formidable-oss-badges` package using corrected types as well as fixing a type cast which shouldn't be needed
Ran docs locally
=> docs: update `formidable-oss-badges` package and usage

packages/extras/docs/components/Loading.md
This PR adds prop docs to the  `Loading` component docs
Ran docs locally
=> docs: Adds prop docs to `Loading` component docs

packages/core/docs/core.md, website/docs/ama/config-file.md
This PR updates core docs to use the new config file methods
=> docs: updated `core` config file details

.changeset/gold-insects-press.md, examples/shared/src/screens/Form.screen.tsx, packages/forms/src/index.ts
This PR fixes a terminal warning from `@babel/plugin-transform-typescript` due to Types not being imported with the type property. 
- Fixes #316
=> fix: terminal warning due to missing type import / exports
